# stdlib!

In [97]:
import csv

conversion_map = {
    'carat': float,
    'depth': float,
    'price': int,
    'table': float,
    'x': float,
    'y': float,
    'z': float
}
def converter(type_map, row):
    """Yep, we need to roll our own type conversions."""
    converted_row = {}
    for col, val in row.items():
        converter = type_map.get(col)
        if converter:
            converted_row[col] = converter(val)
        else:
            converted_row[col] = val
    return converted_row

with open('diamonds.csv', 'r') as f:
    reader = csv.DictReader(f)
    diamonds = [converter(conversion_map, r) for r in reader]

In [98]:
diamonds[:2]

[{'': '1',
  'carat': 0.23,
  'clarity': 'SI2',
  'color': 'E',
  'cut': 'Ideal',
  'depth': 61.5,
  'price': 326,
  'table': 55.0,
  'x': 3.95,
  'y': 3.98,
  'z': 2.43},
 {'': '2',
  'carat': 0.21,
  'clarity': 'SI1',
  'color': 'E',
  'cut': 'Premium',
  'depth': 59.8,
  'price': 326,
  'table': 61.0,
  'x': 3.89,
  'y': 3.84,
  'z': 2.31}]

Adding things up is easy enough...

In [99]:
def get_total_carats():
    total_carats = 0
    for row in diamonds:
        total_carats += row['carat']
    return total_carats
get_total_carats()

43040.86999999912

In [100]:
# Faster/more compact: Generator expression!
sum(row['carat'] for row in diamonds)

43040.86999999912

In [101]:
# Which is faster? 
%timeit get_total_carats()

100 loops, best of 3: 6.46 ms per loop


In [102]:
%timeit sum(row['carat'] for row in diamonds)

100 loops, best of 3: 6.76 ms per loop


But what if we want to group, then add?

In [103]:
# defaultdict is awesome. defaultdict is awesome.
from collections import defaultdict

def grouper(grouping_col, seq):
    """Surely someone has written a faster version than what I'm about to write"""
    groups = {}
    for row in seq:
        group = groups.get(row[grouping_col])
        if group is not None:
            for k, v in row.items():
                if k != grouping_col:
                    group[k].append(v)
        else:
            groups[row[grouping_col]] = defaultdict(list)
    return groups

In [104]:
groups = grouper('cut', diamonds)

In [105]:
set(groups)

{'Fair', 'Good', 'Ideal', 'Premium', 'Very Good'}

What if I wanted to do something like 
```sql
select cut, mean(price)
from diamonds
groupby cut;
```

In [106]:
summary = {}
for group, values in groups.items():
    summary[group] = sum(values['price']) / len(values['price'])
summary

{'Fair': 4361, 'Good': 3929, 'Ideal': 3457, 'Premium': 4584, 'Very Good': 3982}

or how about this one:
```sql
select max(price)
from diamonds
where carat > 1;
```

In [107]:
def get_max_price():
    max_price = 0
    for row in diamonds:
        if row['carat'] > 1 and row['price'] > max_price:
            max_price = row['price']
    return max_price
get_max_price()

18823

In [108]:
# More compact yet again: generator expression!
max(row['price'] for row in diamonds if row['carat'] > 1)

18823

In [109]:
# Which is faster?
%timeit get_max_price()

100 loops, best of 3: 8.38 ms per loop


In [110]:
%timeit max(row['price'] for row in diamonds if row['carat'] > 1)

100 loops, best of 3: 9.22 ms per loop


### itertools interlude

The itertools module does lots of nice things. You should be aware of it, and use it where you would be writing your own bespoke counting thing. 

# Toolz!

Lets see what it looks like to repeat some of this analysis using the toolz library. PSA: toolz has a pretty huge API, and it's worth reading through the docs: http://toolz.readthedocs.org/en/latest/api.html

In [111]:
import toolz as tz

Some quick toolz fun things:

In [112]:
list(tz.concat(([1, 2, 3], (4, 5, 6))))

[1, 2, 3, 4, 5, 6]

In [113]:
list(tz.mapcat(lambda r: [x + "-foo" for x in r],
                          [["A", "B"], ("c", "d"), ("bar", "baz")]))

['A-foo', 'B-foo', 'c-foo', 'd-foo', 'bar-foo', 'baz-foo']

In [114]:
tz.frequencies([r['color'] for r in diamonds])

{'D': 6775, 'E': 9797, 'F': 9542, 'G': 11292, 'H': 8304, 'I': 5422, 'J': 2808}

Remember that toolz is lazy- functions will return generator-like things:

In [115]:
take_2 = tz.take(2, diamonds)
take_2

In [116]:
unique_clarity = tz.unique(diamonds, key=lambda x: x.get('clarity'))
unique_clarity

<generator object unique at 0x10b6be500>

In [117]:
list(take_2)

[{'': '1',
  'carat': 0.23,
  'clarity': 'SI2',
  'color': 'E',
  'cut': 'Ideal',
  'depth': 61.5,
  'price': 326,
  'table': 55.0,
  'x': 3.95,
  'y': 3.98,
  'z': 2.43},
 {'': '2',
  'carat': 0.21,
  'clarity': 'SI1',
  'color': 'E',
  'cut': 'Premium',
  'depth': 59.8,
  'price': 326,
  'table': 61.0,
  'x': 3.89,
  'y': 3.84,
  'z': 2.31}]

In [118]:
# Note that this returns the entire object
list(unique_clarity)

[{'': '1',
  'carat': 0.23,
  'clarity': 'SI2',
  'color': 'E',
  'cut': 'Ideal',
  'depth': 61.5,
  'price': 326,
  'table': 55.0,
  'x': 3.95,
  'y': 3.98,
  'z': 2.43},
 {'': '2',
  'carat': 0.21,
  'clarity': 'SI1',
  'color': 'E',
  'cut': 'Premium',
  'depth': 59.8,
  'price': 326,
  'table': 61.0,
  'x': 3.89,
  'y': 3.84,
  'z': 2.31},
 {'': '3',
  'carat': 0.23,
  'clarity': 'VS1',
  'color': 'E',
  'cut': 'Good',
  'depth': 56.9,
  'price': 327,
  'table': 65.0,
  'x': 4.05,
  'y': 4.07,
  'z': 2.31},
 {'': '4',
  'carat': 0.29,
  'clarity': 'VS2',
  'color': 'I',
  'cut': 'Premium',
  'depth': 62.4,
  'price': 334,
  'table': 58.0,
  'x': 4.2,
  'y': 4.23,
  'z': 2.63},
 {'': '6',
  'carat': 0.24,
  'clarity': 'VVS2',
  'color': 'J',
  'cut': 'Very Good',
  'depth': 62.8,
  'price': 336,
  'table': 57.0,
  'x': 3.94,
  'y': 3.96,
  'z': 2.48},
 {'': '7',
  'carat': 0.24,
  'clarity': 'VVS1',
  'color': 'I',
  'cut': 'Very Good',
  'depth': 62.3,
  'price': 336,
  'table': 57

In [119]:
# What are our clarity counts?
tz.countby(lambda x: x['clarity'], diamonds)

{'I1': 741,
 'IF': 1790,
 'SI1': 13065,
 'SI2': 9194,
 'VS1': 8171,
 'VS2': 12258,
 'VVS1': 3655,
 'VVS2': 5066}

In [120]:
# What about our max price from above? Reduction!
def comparo(accum, row):
    price = row['price']
    if price > accum:
        return price
    else:
        return accum
    
tz.reduce(comparo, diamonds, 0)

18823

In [121]:
# We could have also threaded here
tz.thread_last(diamonds, 
               (tz.map, lambda x: x['price']), 
               max)

18823

In [122]:
# Which is faster?
%timeit tz.reduce(comparo, diamonds, 0)

100 loops, best of 3: 12.1 ms per loop


In [123]:
%timeit tz.thread_last(diamonds, (tz.map, lambda x: x['price']), max)

100 loops, best of 3: 14.6 ms per loop


Let's look at another SQL query- say we want clarity and carats where price > 1000:
```sql
select count(1)
from diamonds
where price > 1000
groupby clarity;
```

In [124]:
# Toolz has currying!
import toolz.curried as tzc
tzc.pipe(diamonds, 
         tzc.filter(lambda r: r['price'] > 1000),
         tzc.map(lambda r: (r['clarity'],)),
         tzc.countby(lambda r: r[0]),
         dict)

{'I1': 675,
 'IF': 1042,
 'SI1': 9978,
 'SI2': 8118,
 'VS1': 5702,
 'VS2': 8647,
 'VVS1': 2108,
 'VVS2': 3146}

In [29]:
# We can go about this another way as well:
def filter_and_count(kv):
    f_and_c = tz.thread_last(kv[1],
                             (tz.filter, lambda r: r['price'] > 1000),
                             tz.count)
                                          
    return kv[0], f_and_c

tz.thread_last(diamonds,
               (tz.groupby, 'clarity'),
               (tz.itemmap, filter_and_count))


{'I1': 675,
 'IF': 1042,
 'SI1': 9978,
 'SI2': 8118,
 'VS1': 5702,
 'VS2': 8647,
 'VVS1': 2108,
 'VVS2': 3146}

In [125]:
# Cleanest/best way: reduceby: Groupby + reduce
def increment(accum, row):
    if row['price'] > 1000:
        return accum + 1
    else:
        return accum

tz.reduceby('clarity', 
            increment,
            diamonds, 0)                               

{'I1': 675,
 'IF': 1042,
 'SI1': 9978,
 'SI2': 8118,
 'VS1': 5702,
 'VS2': 8647,
 'VVS1': 2108,
 'VVS2': 3146}

# Pandas!

In [31]:
import pandas as pd
# We don't need this to use Pandas, FYI
import numpy as np

# CSV reader is fast!
df = pd.read_csv('diamonds.csv', index_col=0)
# Keep this for later, we're going to overwrite df
df_diamonds = df

In [32]:
df.head()

carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5     55    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8     61    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9     65    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4     58    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3     58    335  4.34  4.35  2.75

In [33]:
df.describe()

carat         depth         table         price             x  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

                  y             z  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [34]:
df.groupby('clarity').mean()

carat      depth      table        price         x         y  \
clarity                                                                    
I1       1.283846  62.734278  58.303779  3924.168691  6.761093  6.709379   
IF       0.505123  61.510615  56.507207  2864.839106  4.968402  4.989827   
SI1      0.850482  61.853042  57.662541  3996.001148  5.888383  5.888256   
SI2      1.077648  61.772167  57.927181  5063.028606  6.401370  6.397826   
VS1      0.727158  61.667458  57.315151  3839.455391  5.572178  5.581828   
VS2      0.763935  61.724417  57.417401  3924.989395  5.657709  5.658859   
VVS1     0.503321  61.624651  56.884460  2523.114637  4.960364  4.975075   
VVS2     0.596202  61.663778  57.024990  3283.737071  5.218454  5.232118   

                z  
clarity            
I1       4.207908  
IF       3.061659  
SI1      3.639845  
SI2      3.948478  
VS1      3.441007  
VS2      3.491478  
VVS1     3.061294  
VVS2     3.221465

Our previous queries:
```sql
select cut, mean(price)
from diamonds
groupby cut;

select count(carat)
from diamonds
where price > 1000
groupby clarity;

select max(price)
from diamonds
where carat > 1;

select cut, price
from diamonds
where cut in ('Ideal', 'Premium')
order by price desc
limit 10;
```

Are pretty trivial operations in Pandas:

In [35]:
df.groupby('cut')['price'].mean()

cut
Fair         4358.757764
Good         3928.864452
Ideal        3457.541970
Premium      4584.257704
Very Good    3981.759891
Name: price, dtype: float64

In [36]:
df[df['price'] > 1000].groupby('clarity')['carat'].count()

clarity
I1       675
IF      1042
SI1     9978
SI2     8118
VS1     5702
VS2     8647
VVS1    2108
VVS2    3146
Name: carat, dtype: int64

In [37]:
df[df['cut'].isin(['Ideal', 'Premium'])].sort('price', ascending=False)[:10]

carat      cut color clarity  depth  table  price     x     y     z
27750   2.29  Premium     I     VS2   60.8     60  18823  8.50  8.47  5.16
27748   1.51    Ideal     G      IF   61.7     55  18806  7.37  7.41  4.56
27747   2.07    Ideal     G     SI2   62.5     55  18804  8.20  8.13  5.11
27745   2.29  Premium     I     SI1   61.8     59  18797  8.52  8.45  5.24
27744   2.00  Premium     I     VS1   60.8     59  18795  8.13  8.02  4.91
27743   2.04  Premium     H     SI1   58.1     60  18795  8.37  8.28  4.84
27742   2.15    Ideal     G     SI2   62.6     54  18791  8.29  8.35  5.21
27741   1.71  Premium     F     VS2   62.3     59  18791  7.57  7.53  4.70
27739   2.05    Ideal     G     SI1   61.9     57  18787  8.10  8.16  5.03
27738   2.05  Premium     F     SI2   60.2     59  18784  8.28  8.33  5.00

In which I do a bunch of cool Pandas things without a real goal

In [38]:
# I can Transpose things!
df.T

1        2     3        4     5          6          7          8      \
carat     0.23     0.21  0.23     0.29  0.31       0.24       0.24       0.26   
cut      Ideal  Premium  Good  Premium  Good  Very Good  Very Good  Very Good   
color        E        E     E        I     J          J          I          H   
clarity    SI2      SI1   VS1      VS2   SI2       VVS2       VVS1        SI1   
depth     61.5     59.8  56.9     62.4  63.3       62.8       62.3       61.9   
table       55       61    65       58    58         57         57         55   
price      326      326   327      334   335        336        336        337   
x         3.95     3.89  4.05      4.2  4.34       3.94       3.95       4.07   
y         3.98     3.84  4.07     4.23  4.35       3.96       3.98       4.11   
z         2.43     2.31  2.31     2.63  2.75       2.48       2.47       2.53   

        9          10     ...      53931    53932      53933      53934  \
carat    0.22       0.23  ...       0.71     0.71        0.7        0.7   
cut      Fair  Very Good  ...    Premium  Premium  Very Good  Very Good   
color       E          H  ...          E        F          E          E   
clarity   VS2        VS1  ...        SI1      SI1        VS2        VS2   
depth    65.1       59.4  ...       60.5     59.8       60.5       61.2   
table      61         61  ...         55       62         59         59   
price     337        338  ...       2756     2756       2757       2757   
x        3.87          4  ...       5.79     5.74       5.71       5.69   
y        3.78       4.05  ...       5.74     5.73       5.76       5.72   
z        2.49       2.39  ...       3.49     3.43       3.47       3.49   

           53935  53936 53937      53938    53939  53940  
carat       0.72   0.72  0.72        0.7     0.86   0.75  
cut      Premium  Ideal  Good  Very Good  Premium  Ideal  
color          D      D     D          D        H      D  
clarity      SI1    SI1   SI1        SI1      SI2    SI2  
depth       62.7   60.8  63.1       62.8       61   62.2  
table         59     57    55         60       58     55  
price       2757   2757  2757       2757     2757   2757  
x           5.69   5.75  5.69       5.66     6.15   5.83  
y           5.73   5.76  5.75       5.68     6.12   5.87  
z           3.58    3.5  3.61       3.56     3.74   3.64  

[10 rows x 53940 columns]

In [39]:
# SORT ALL THE THINGS!
df.sort(['price', 'carat'], ascending=False).head()

carat        cut color clarity  depth  table  price     x     y     z
27750   2.29    Premium     I     VS2   60.8     60  18823  8.50  8.47  5.16
27749   2.00  Very Good     G     SI1   63.5     56  18818  7.90  7.97  5.04
27748   1.51      Ideal     G      IF   61.7     55  18806  7.37  7.41  4.56
27747   2.07      Ideal     G     SI2   62.5     55  18804  8.20  8.13  5.11
27746   2.00  Very Good     H     SI1   62.8     57  18803  7.95  8.00  5.01

In [40]:
# Lets use some fake data to show off some stuff:
simple_data_1 = {"int_col": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 "str_col": ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"],
                 "float_col": [1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5, 10.5],
                 "time_col": ["2015-01-01", "2015-01-02", "2015-01-03", "2015-01-04", "2015-01-05",
                              "2015-01-06", "2015-01-07", "2015-01-08", "2015-01-09", "2015-01-10"]}
my_index = ["a", "b", "c", "a", "b", "c", "a", "b", "c", "a"]
df = pd.DataFrame(simple_data_1, index=my_index)
df

float_col  int_col str_col    time_col
a        1.5        1       a  2015-01-01
b        2.5        2       b  2015-01-02
c        3.5        3       c  2015-01-03
a        4.5        4       d  2015-01-04
b        5.5        5       e  2015-01-05
c        6.5        6       f  2015-01-06
a        7.5        7       g  2015-01-07
b        8.5        8       h  2015-01-08
c        9.5        9       i  2015-01-09
a       10.5       10       j  2015-01-10

In [41]:
# DataFrames have indices that can be gotten by label or position
df.loc['a']

float_col  int_col str_col    time_col
a        1.5        1       a  2015-01-01
a        4.5        4       d  2015-01-04
a        7.5        7       g  2015-01-07
a       10.5       10       j  2015-01-10

In [42]:
df.iloc[5]

float_col           6.5
int_col               6
str_col               f
time_col     2015-01-06
Name: c, dtype: object

In [43]:
df[2:4]

float_col  int_col str_col    time_col
c        3.5        3       c  2015-01-03
a        4.5        4       d  2015-01-04

In [44]:
# New Column! With Missing Data!
df['new_col'] = [np.nan, np.nan, 1.0, 2.0, np.nan, 4.0, 5.0, 9.0, np.nan, 10.0]
df

float_col  int_col str_col    time_col  new_col
a        1.5        1       a  2015-01-01      NaN
b        2.5        2       b  2015-01-02      NaN
c        3.5        3       c  2015-01-03        1
a        4.5        4       d  2015-01-04        2
b        5.5        5       e  2015-01-05      NaN
c        6.5        6       f  2015-01-06        4
a        7.5        7       g  2015-01-07        5
b        8.5        8       h  2015-01-08        9
c        9.5        9       i  2015-01-09      NaN
a       10.5       10       j  2015-01-10       10

In [45]:
# Removing missing data!
df.dropna()

float_col  int_col str_col    time_col  new_col
c        3.5        3       c  2015-01-03        1
a        4.5        4       d  2015-01-04        2
c        6.5        6       f  2015-01-06        4
a        7.5        7       g  2015-01-07        5
b        8.5        8       h  2015-01-08        9
a       10.5       10       j  2015-01-10       10

In [46]:
# Fill missing data!
df.fillna("FOO!")

float_col  int_col str_col    time_col new_col
a        1.5        1       a  2015-01-01    FOO!
b        2.5        2       b  2015-01-02    FOO!
c        3.5        3       c  2015-01-03       1
a        4.5        4       d  2015-01-04       2
b        5.5        5       e  2015-01-05    FOO!
c        6.5        6       f  2015-01-06       4
a        7.5        7       g  2015-01-07       5
b        8.5        8       h  2015-01-08       9
c        9.5        9       i  2015-01-09    FOO!
a       10.5       10       j  2015-01-10      10

In [47]:
# Backfill missing data!
df.fillna(method='bfill')

float_col  int_col str_col    time_col  new_col
a        1.5        1       a  2015-01-01        1
b        2.5        2       b  2015-01-02        1
c        3.5        3       c  2015-01-03        1
a        4.5        4       d  2015-01-04        2
b        5.5        5       e  2015-01-05        4
c        6.5        6       f  2015-01-06        4
a        7.5        7       g  2015-01-07        5
b        8.5        8       h  2015-01-08        9
c        9.5        9       i  2015-01-09       10
a       10.5       10       j  2015-01-10       10

In [48]:
# Vectorized string methods!
df['str_col'] = ["FOO", "FoO", "Foo", "Fo o", "FOO", "fOO", "fOo", "FoO", "foO", "Foo   "]
df

float_col  int_col str_col    time_col  new_col
a        1.5        1     FOO  2015-01-01      NaN
b        2.5        2     FoO  2015-01-02      NaN
c        3.5        3     Foo  2015-01-03        1
a        4.5        4    Fo o  2015-01-04        2
b        5.5        5     FOO  2015-01-05      NaN
c        6.5        6     fOO  2015-01-06        4
a        7.5        7     fOo  2015-01-07        5
b        8.5        8     FoO  2015-01-08        9
c        9.5        9     foO  2015-01-09      NaN
a       10.5       10  Foo     2015-01-10       10

In [49]:
df['str_col'].str.lower().str.replace(' ', '')

a    foo
b    foo
c    foo
a    foo
b    foo
c    foo
a    foo
b    foo
c    foo
a    foo
Name: str_col, dtype: object

In [50]:
# Database style joins!!
left = pd.DataFrame({'key': ['foo', 'bar', 'fizz'], 'lval': [1, 2, 3]})
right = pd.DataFrame({'key': ['foo', 'bar', 'baz', 'qux'], 
                      'rval': [4, 5, 6, 7]})
left.merge(right, how='inner')

key  lval  rval
0  foo     1     4
1  bar     2     5

In [51]:
right.merge(left, how='outer')

key  rval  lval
0   foo     4     1
1   bar     5     2
2   baz     6   NaN
3   qux     7   NaN
4  fizz   NaN     3

In [52]:
left.merge(right, how='left')

key  lval  rval
0   foo     1     4
1   bar     2     5
2  fizz     3   NaN

In [53]:
# Lets make some random timeseries data
dates = pd.date_range('2015-03-25', periods=150, freq='H')
dates

<class 'pandas.tseries.index.DatetimeIndex'>
[2015-03-25 00:00:00, ..., 2015-03-31 05:00:00]
Length: 150, Freq: H, Timezone: None

In [54]:
time_df = pd.DataFrame(np.random.randint(0, 500, 150), index=dates, columns=["Numeric"])
time_df.head()

Numeric
2015-03-25 00:00:00      224
2015-03-25 01:00:00      124
2015-03-25 02:00:00        6
2015-03-25 03:00:00      140
2015-03-25 04:00:00      130

In [55]:
# RESAMPLE!
time_df.resample('D', how='mean')

Numeric
2015-03-25  239.208333
2015-03-26  295.541667
2015-03-27  246.791667
2015-03-28  222.250000
2015-03-29  262.458333
2015-03-30  246.125000
2015-03-31  265.500000

In [56]:
# Convert weird date formats!
the_worst = ['3/25/2014 23:02:00', '2014-03-25 23:01:00', 'March 25 2015']
pd.to_datetime(the_worst)

<class 'pandas.tseries.index.DatetimeIndex'>
[2014-03-25 23:02:00, ..., 2015-03-25 00:00:00]
Length: 3, Freq: None, Timezone: None

In [57]:
# Shift dates!
time_df.shift(1, freq='D').head()

Numeric
2015-03-26 00:00:00      224
2015-03-26 01:00:00      124
2015-03-26 02:00:00        6
2015-03-26 03:00:00      140
2015-03-26 04:00:00      130

In [58]:
# What if I have missing dates?
missing = pd.to_datetime(['2015-03-25', '2015-03-30', '2015-04-05'])
missing_df = pd.DataFrame(np.random.randint(0, 10, 3), index=missing, columns=["Numeric"])
missing_df

Numeric
2015-03-25        0
2015-03-30        7
2015-04-05        9

In [59]:
missing_df.asfreq('D')

Numeric
2015-03-25        0
2015-03-26      NaN
2015-03-27      NaN
2015-03-28      NaN
2015-03-29      NaN
2015-03-30        7
2015-03-31      NaN
2015-04-01      NaN
2015-04-02      NaN
2015-04-03      NaN
2015-04-04      NaN
2015-04-05        9

In [60]:
missing_df.asfreq('D', method='pad')

Numeric
2015-03-25        0
2015-03-26        0
2015-03-27        0
2015-03-28        0
2015-03-29        0
2015-03-30        7
2015-03-31        7
2015-04-01        7
2015-04-02        7
2015-04-03        7
2015-04-04        7
2015-04-05        9

#XRAY!

In [61]:
import xray

In [62]:
arr = np.array([[1, 2, 3, 4], 
                [10, 20, 30, 40],
                [100, 200, 300, 400]])
dim0_coords = ['a', 'b', 'c']
dim1_coords = ['foo', 'bar', 'baz', 'qux']
da = xray.DataArray(arr, [('x', dim0_coords), ('y', dim1_coords)])
da

<xray.DataArray (x: 3, y: 4)>
array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [63]:
# Arrays!
da.values

array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])

In [64]:
da.dims

('x', 'y')

In [65]:
da.coords

Coordinates:
  * x        (x) |S1 'a' 'b' 'c'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [66]:
# But with some Pandas-like powers!

# Index by slice
da[0:2]

<xray.DataArray (x: 2, y: 4)>
array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])
Coordinates:
  * x        (x) |S1 'a' 'b'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [67]:
# Indexing!
da.loc['a']

<xray.DataArray (y: 4)>
array([1, 2, 3, 4])
Coordinates:
    x        |S1 'a'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [68]:
da.loc['a':'c']

<xray.DataArray (x: 3, y: 4)>
array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [69]:
da.sel(x=['a', 'c'])

<xray.DataArray (x: 2, y: 4)>
array([[  1,   2,   3,   4],
       [100, 200, 300, 400]])
Coordinates:
  * x        (x) |S1 'a' 'c'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [70]:
da.sel(y='foo')

<xray.DataArray (x: 3)>
array([  1,  10, 100])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'
    y        |S3 'foo'

In [71]:
da.isel(x=0)

<xray.DataArray (y: 4)>
array([1, 2, 3, 4])
Coordinates:
    x        |S1 'a'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [72]:
# Do numpy stuff
np.mean(da), np.sum(da)

(<xray.DataArray ()>
 array(92.5), <xray.DataArray ()>
 array(1110))

In [73]:
np.sin(da)

<xray.DataArray (x: 3, y: 4)>
array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.54402111,  0.91294525, -0.98803162,  0.74511316],
       [-0.50636564, -0.8732973 , -0.99975584, -0.85091936]])
Coordinates:
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'
  * x        (x) |S1 'a' 'b' 'c'

In [74]:
# Broadcast!
da + 100

<xray.DataArray (x: 3, y: 4)>
array([[101, 102, 103, 104],
       [110, 120, 130, 140],
       [200, 300, 400, 500]])
Coordinates:
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'
  * x        (x) |S1 'a' 'b' 'c'

In [75]:
# Do all of the above by label
da.mean(dim='x')

<xray.DataArray (y: 4)>
array([  37.,   74.,  111.,  148.])
Coordinates:
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [76]:
da.sum(dim='y')

<xray.DataArray (x: 3)>
array([  10,  100, 1000])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'

In [77]:
da

<xray.DataArray (x: 3, y: 4)>
array([[  1,   2,   3,   4],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400]])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

In [78]:
# Group stuff
da.groupby('x').mean()

<xray.DataArray (x: 3)>
array([   2.5,   25. ,  250. ])
Coordinates:
  * x        (x) |S1 'a' 'b' 'c'

In [79]:
da.groupby('y').sum()

<xray.DataArray (y: 4)>
array([111, 222, 333, 444])
Coordinates:
  * y        (y) |S3 'foo' 'bar' 'baz' 'qux'

#Blaze

For this demo, we're going to focus on a couple queries we used in the Pandas demo:
```
select cut, mean(price)
from diamonds
groupby cut;

select count(carat)
from diamonds
where price > 1000
group by clarity;
```

In [80]:
import blaze as bz

diamonds = bz.symbol('diamonds', bz.discover(df_diamonds))

In [81]:
mean_price = bz.by(diamonds.cut, price=diamonds.price.mean())
carat_count = bz.by(diamonds[diamonds.price > 1000].clarity,
                    carat=diamonds.carat.count())

In [82]:
# We haven't actually computed anything yet!
# Let's make Pandas compute it. 
bz.compute(mean_price, df_diamonds)

cut        price
0       Fair  4358.757764
1       Good  3928.864452
2      Ideal  3457.541970
3    Premium  4584.257704
4  Very Good  3981.759891

In [83]:
bz.compute(carat_count, df_diamonds)

clarity  carat
0      I1    741
1      IF   1790
2     SI1  13065
3     SI2   9194
4     VS1   8171
5     VS2  12258
6    VVS1   3655
7    VVS2   5066

Ok, so what? You made Pandas do a thing we already did. 

### Oh Yeah, what if we want Postgres to compute it? 

## WAT

In [84]:
# Blaze/Odo make it easy to move data between containers
# Note that we have an empty table already created
pg_datasource = bz.odo(df_diamonds, "postgresql://postgres:postgres@localhost/pydata::diamonds")

In [85]:
# Now we're going to use Postgres as our computation engine
bz.odo(bz.compute(carat_count, pg_datasource), pd.DataFrame)

f0     f1
0    IF   1790
1    I1    741
2  VVS1   3655
3   VS2  12258
4   VS1   8171
5  VVS2   5066
6   SI2   9194
7   SI1  13065

You can use any SQL supported by SQLAlchemy as your computation. It also supports MongoDB. 

So what about Out-of-Core?

In [86]:
# Blaze is doing it for you!
from blaze.expr.split import split
split(diamonds, carat_count)

((chunk, by(chunk[chunk.price > 1000].clarity, carat=count(chunk.carat))),
 (aggregate, by(aggregate.clarity, carat=sum(aggregate.carat))))

This diamonds dataset not quite big enough to trigger it, but if you really want, you can provide your own Multiprocessing pool: 

In [87]:
import multiprocessing  
pool = multiprocessing.Pool(4)
bz.compute(carat_count, df_diamonds, map=pool)

clarity  carat
0      I1    741
1      IF   1790
2     SI1  13065
3     SI2   9194
4     VS1   8171
5     VS2  12258
6    VVS1   3655
7    VVS2   5066

# bcolz!

In [88]:
import bcolz

dc = bcolz.ctable.fromdataframe(df_diamonds)
dc

ctable((53940,), [('carat', '<f8'), ('cut', 'S9'), ('color', 'S1'), ('clarity', 'S4'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])
  nbytes: 3.60 MB; cbytes: 3.49 MB; ratio: 1.03
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[(0.23, 'Ideal', 'E', 'SI2', 61.5, 55.0, 326, 3.95, 3.98, 2.43)
 (0.21, 'Premium', 'E', 'SI1', 59.8, 61.0, 326, 3.89, 3.84, 2.31)
 (0.23, 'Good', 'E', 'VS1', 56.9, 65.0, 327, 4.05, 4.07, 2.31) ...,
 (0.7, 'Very Good', 'D', 'SI1', 62.8, 60.0, 2757, 5.66, 5.68, 3.56)
 (0.86, 'Premium', 'H', 'SI2', 61.0, 58.0, 2757, 6.15, 6.12, 3.74)
 (0.75, 'Ideal', 'D', 'SI2', 62.2, 55.0, 2757, 5.83, 5.87, 3.64)]

In [89]:
dc.cols

carat : carray((53940,), float64)
  nbytes: 421.41 KB; cbytes: 468.10 KB; ratio: 0.90
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[ 0.23  0.21  0.23 ...,  0.7   0.86  0.75]
cut : carray((53940,), |S9)
  nbytes: 474.08 KB; cbytes: 315.96 KB; ratio: 1.50
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
['Ideal' 'Premium' 'Good' ..., 'Very Good' 'Premium' 'Ideal']
color : carray((53940,), |S1)
  nbytes: 52.68 KB; cbytes: 128.00 KB; ratio: 0.41
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
['E' 'E' 'E' ..., 'D' 'H' 'D']
clarity : carray((53940,), |S4)
  nbytes: 210.70 KB; cbytes: 256.00 KB; ratio: 0.82
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
['SI2' 'SI1' 'VS1' ..., 'SI1' 'SI2' 'SI2']
depth : carray((53940,), float64)
  nbytes: 421.41 KB; cbytes: 407.65 KB; ratio: 1.03
  cparams := cparams(clevel=5, shuffle=True, cname='blosclz')
[ 61.5  59.8  56.9 ...,  62.8  61.   62.2]
table : carray((53940,), float64)
  nbytes: 421.41 

In [90]:
dsize = dc.cbytes / 2**20.
print("Total size for the ctable: {} MB".format(dsize))
print("Compression ratio the ctable: {}".format((dc.nbytes / float(dc.cbytes))))

Total size for the ctable: 3.49322795868 MB
Compression ratio the ctable: 1.03081835096


In [91]:
# You can do DataFrame-like stuff
dc["cut == 'Ideal'"]

array([(0.23, 'Ideal', 'E', 'SI2', 61.5, 55.0, 326, 3.95, 3.98, 2.43),
       (0.23, 'Ideal', 'J', 'VS1', 62.8, 56.0, 340, 3.93, 3.9, 2.46),
       (0.31, 'Ideal', 'J', 'SI2', 62.2, 54.0, 344, 4.35, 4.37, 2.71), ...,
       (0.71, 'Ideal', 'G', 'VS1', 61.4, 56.0, 2756, 5.76, 5.73, 3.53),
       (0.72, 'Ideal', 'D', 'SI1', 60.8, 57.0, 2757, 5.75, 5.76, 3.5),
       (0.75, 'Ideal', 'D', 'SI2', 62.2, 55.0, 2757, 5.83, 5.87, 3.64)], 
      dtype=[('carat', '<f8'), ('cut', 'S9'), ('color', 'S1'), ('clarity', 'S4'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

In [92]:
dc["(cut == 'Ideal') & (price > 1000)"]

array([(0.7, 'Ideal', 'E', 'SI1', 62.5, 57.0, 2757, 5.7, 5.72, 3.57),
       (0.7, 'Ideal', 'G', 'VS2', 61.6, 56.0, 2757, 5.7, 5.67, 3.5),
       (0.74, 'Ideal', 'G', 'SI1', 61.6, 55.0, 2760, 5.8, 5.85, 3.59), ...,
       (0.71, 'Ideal', 'G', 'VS1', 61.4, 56.0, 2756, 5.76, 5.73, 3.53),
       (0.72, 'Ideal', 'D', 'SI1', 60.8, 57.0, 2757, 5.75, 5.76, 3.5),
       (0.75, 'Ideal', 'D', 'SI2', 62.2, 55.0, 2757, 5.83, 5.87, 3.64)], 
      dtype=[('carat', '<f8'), ('cut', 'S9'), ('color', 'S1'), ('clarity', 'S4'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

In [93]:
# We can do the same thing with the ctable on disk!
diskdc = dc.copy(rootdir='diamonds')

In [94]:
diskdc["(cut == 'Ideal') & (price > 1000)"]

array([(0.7, 'Ideal', 'E', 'SI1', 62.5, 57.0, 2757, 5.7, 5.72, 3.57),
       (0.7, 'Ideal', 'G', 'VS2', 61.6, 56.0, 2757, 5.7, 5.67, 3.5),
       (0.74, 'Ideal', 'G', 'SI1', 61.6, 55.0, 2760, 5.8, 5.85, 3.59), ...,
       (0.71, 'Ideal', 'G', 'VS1', 61.4, 56.0, 2756, 5.76, 5.73, 3.53),
       (0.72, 'Ideal', 'D', 'SI1', 60.8, 57.0, 2757, 5.75, 5.76, 3.5),
       (0.75, 'Ideal', 'D', 'SI2', 62.2, 55.0, 2757, 5.83, 5.87, 3.64)], 
      dtype=[('carat', '<f8'), ('cut', 'S9'), ('color', 'S1'), ('clarity', 'S4'), ('depth', '<f8'), ('table', '<f8'), ('price', '<i8'), ('x', '<f8'), ('y', '<f8'), ('z', '<f8')])

In [95]:
import os

for root, dirs, files in os.walk('diamonds'):
    level = root.replace('diamonds', '').count(os.sep)
    indent = ' ' * 4 * (level)
    print('{}{}/'.format(indent, os.path.basename(root)))
    subindent = ' ' * 4 * (level + 1)
    for f in files:
        print('{}{}'.format(subindent, f))

diamonds/
    __attrs__
    __rootdirs__
    carat/
        __attrs__
        data/
            __0.blp
            __1.blp
        meta/
            sizes
            storage
    clarity/
        __attrs__
        data/
            __0.blp
        meta/
            sizes
            storage
    color/
        __attrs__
        data/
            __0.blp
        meta/
            sizes
            storage
    cut/
        __attrs__
        data/
            __0.blp
            __1.blp
        meta/
            sizes
            storage
    depth/
        __attrs__
        data/
            __0.blp
            __1.blp
        meta/
            sizes
            storage
    price/
        __attrs__
        data/
            __0.blp
            __1.blp
        meta/
            sizes
            storage
    table/
        __attrs__
        data/
            __0.blp
            __1.blp
        meta/
            sizes
            storage
    x/
        __attrs__
        data/
            __0